package de.valendur.discordbot.configs;

import kong.unirest.json.JSONObject;

public class BaseConfig extends GenericConfig {

	public String COMMAND_PREFIX, BACKEND_LINK, ERROR_CHANNEL, BIRTHDAY_CHANNEL,
					BIRTHDAY_MESSAGE, BIRTHDAY_ROLE_ID, TWITCH_ANNOUNCEMENT_CHANNEL,
					SM_ROLE_ID, TWITCH_CHANNEL_NAME;
	
	public int SCHEDULING_LEVELING_RESET_HOUR, SCHEDULING_LEVELING_RESET_MINUTE, SCHEDULING_LEVELING_RESET_SECOND,
			SCHEDULING_VOICE_CHECK;
	
	public BaseConfig(ConfigType type) {
		super(type);
	}

	@Override
	public void load() {
		JSONObject config = readConfig();
		COMMAND_PREFIX = config.getString("COMMAND_PREFIX");
		BACKEND_LINK = config.getString("BACKEND_LINK");
		ERROR_CHANNEL = config.getString("ERROR_CHANNEL");
		
		
		
		BIRTHDAY_CHANNEL = config.getString("BIRTHDAY_CHANNEL");
		BIRTHDAY_MESSAGE = config.getString("BIRTHDAY_MESSAGE");
		BIRTHDAY_ROLE_ID = config.getString("BIRTHDAY_ROLE_ID");
		TWITCH_ANNOUNCEMENT_CHANNEL = config.getString("TWITCH_ANNOUNCEMENT_CHANNEL");
		TWITCH_CHANNEL_NAME = config.getString("TWITCH_CHANNEL_NAME");
		SM_ROLE_ID = config.getString("SM_ROLE_ID");
		
		JSONObject SCHEDULING = config.getJSONObject("SCHEDULER");
		
		JSONObject SCHEDULING_LEVELING_RESET = SCHEDULING.getJSONObject("LEVELING_RESET");
		SCHEDULING_LEVELING_RESET_HOUR = SCHEDULING_LEVELING_RESET.getInt("HOUR");
		SCHEDULING_LEVELING_RESET_MINUTE = SCHEDULING_LEVELING_RESET.getInt("MINUTE");
		SCHEDULING_LEVELING_RESET_SECOND = SCHEDULING_LEVELING_RESET.getInt("SECOND");
		
		SCHEDULING_VOICE_CHECK = SCHEDULING.getInt("VOICE_CHECK_EVERY_SECONDS");
		
	}
	

}
